---
- name: MyApp GCE セットアップ
  hosts: all
  become: true

  roles:
    - { role: common, tags: ['common'] }
    - { role: cloud-sql-proxy, tags: ['cloud-sql-proxy'] }
    - { role: db-config, tags: ['db-config'] }
    - { role: apache, tags: ['apache'] }
    - { role: webapp, tags: ['webapp'] }
    - { role: ops-agent, tags: ['ops-agent'] }
